In [1]:
import torch
from torch import nn, optim

In [2]:
from torch.distributions  import Exponential, Normal

In [3]:
from sklearn.preprocessing import QuantileTransformer

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [69]:
x = torch.tensor([1.0],  requires_grad=True)

In [73]:
y = 2 * x
y.requires_grad
# y.retain_grad()

True

In [90]:
z = y
print(y.requires_grad, z.requires_grad)
z.retain_grad()
z.add_(1)
z.retain_grad()
print(z.requires_grad, z.grad)
# z, y

True True
True None


In [91]:
w = z**2
w

tensor([16.], grad_fn=<PowBackward0>)

In [92]:
w.backward()

In [93]:
x.grad, y.grad, z.grad

(tensor([16.]), tensor([8.]), tensor([8.]))

In [98]:
x = torch.tensor([-1.0],  requires_grad=True)
y = torch.where(x  > 0, x*2, x*0)  # 所有分支被记录
 
y.backward()       # 梯度仅沿实际执行路径传播

In [99]:
x.grad

tensor([0.])